development:
  adapter: postgresql
  encoding: unicode
  database: despesas_parlamentares_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: despesas_parlamentares_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  pool: 25
  host: <%= ENV['POSTGRESQL_URL'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>